name: AWS OpenId Credentials

on:
    push:
    workflow_dispatch:

jobs:
    job1:
        runs-on: windows-latest
        steps:
            - name: Configuring AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: us-east-1
                role-to-assume: arn:aws:iam::092376285579:role/github-actions-oidc
            - run: |
                Install-Module -Name AWS.Tools.EC2 -Force
                Get-EC2Vpc